title: Amit Agarwal
name: Amit Agarwal
description: Principal Applied Scientist at Oracle Cloud Infrastructure
url: https://iamamitagarwal.github.io
baseurl: ""

remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: default

markdown: kramdown
permalink: /:categories/:title/
include:
  - _pages

plugins:
  - jekyll-include-cache

author:
  name: "Amit Agarwal"
  avatar: "/images/profile.jpeg"
  bio: "Principal Applied Scientist at Oracle Cloud Infrastructure (OCI). Applied ML/LLMs and cloud-scale systems."
  location: "Seattle, WA"
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=Mc9RC6QAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/amitagarwal6/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/iamamitagarwal"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

collections:
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/
